name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output the name of the event that triggered the workflow
        run: |
          echo "Workflow triggered by event: ${{ github.event_name }}"
      
      - name: Output the name of the branch that the repository is currently referencing
        run: |    
          echo "Name of the branch the repo is referencing: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0
      
      - name: List all files in the repository
        run: |
          echo "The repo contains following files:"
          tree
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: build
    environment: Test
    steps:
      - name: Testing 
        run: echo "Testing..."
  
  load-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: build
    environment: Load-Test
    steps:
      - name: Testing and sleeping
        run: |
          echo "Testing..."
          sleep 15

  production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Production'
    needs: [test, load-test]
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - name: First step
        run: |
          echo "Step 1 running..."
          sleep 10
      - name: Second step
        run: |
          echo "Step 2 running..."
          sleep 10
      - name: Third step
        run: |
          echo "Step 3 running..."
          sleep 10
      - name: Fourth step
        run: |
          echo "Step 4 running..."
          sleep 10
      - name: Fifth step
        run: |
          echo "Step 4 running..."
          sleep 10    
